# Generated by Django 4.0.6 on 2022-08-08 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0153_created_datetimefield'),
        ('netbox_qrcode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrextendeddevice',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dcim.location'),
        ),
        migrations.AddField(
            model_name='qrextendeddevice',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dcim.region'),
        ),
        migrations.AddField(
            model_name='qrextendedlocation',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dcim.site'),
        ),
        migrations.AddField(
            model_name='qrextendedrack',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dcim.location'),
        ),
    ]
