# Generated by Django 3.2 on 2021-06-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_qrcode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrextendedcable',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
