# Generated by Django 3.2 on 2021-04-20 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_qrcode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrextendedcable',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='qrextendedrack',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
