# Generated by Django 3.1.7 on 2021-04-03 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0122_standardize_name_length'),
        ('netbox_qrcode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='netboxobject',
            name='peer_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='netboxobject',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dcim.site'),
        ),
    ]
