# Generated by Django 3.2 on 2021-04-20 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_qrcode', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrextendedcable',
            name='label',
        ),
    ]
