# Generated by Django 4.0.7 on 2022-08-09 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_qrcode', '0002_qrextendeddevice_location_qrextendeddevice_region_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrextendedcable',
            name='name',
        ),
        migrations.RemoveField(
            model_name='qrextendeddevice',
            name='device_role',
        ),
        migrations.RemoveField(
            model_name='qrextendeddevice',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='qrextendeddevice',
            name='location',
        ),
        migrations.RemoveField(
            model_name='qrextendeddevice',
            name='name',
        ),
        migrations.RemoveField(
            model_name='qrextendeddevice',
            name='rack',
        ),
        migrations.RemoveField(
            model_name='qrextendeddevice',
            name='region',
        ),
        migrations.RemoveField(
            model_name='qrextendeddevice',
            name='site',
        ),
        migrations.RemoveField(
            model_name='qrextendeddevice',
            name='status',
        ),
        migrations.RemoveField(
            model_name='qrextendedlocation',
            name='name',
        ),
        migrations.RemoveField(
            model_name='qrextendedlocation',
            name='site',
        ),
        migrations.RemoveField(
            model_name='qrextendedrack',
            name='location',
        ),
        migrations.RemoveField(
            model_name='qrextendedrack',
            name='name',
        ),
        migrations.RemoveField(
            model_name='qrextendedrack',
            name='role',
        ),
        migrations.RemoveField(
            model_name='qrextendedrack',
            name='site',
        ),
        migrations.RemoveField(
            model_name='qrextendedrack',
            name='status',
        ),
    ]
