# Generated by Django 3.1.7 on 2021-04-03 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_qrcode', '0002_auto_20210403_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='netboxobject',
            name='peer_name',
        ),
        migrations.RemoveField(
            model_name='netboxobject',
            name='site',
        ),
    ]
