# Generated by Django 3.1.7 on 2021-04-04 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_qrcode_ui', '0004_auto_20210404_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrextendedcable',
            name='photo',
            field=models.ImageField(upload_to='opt/netbox/netbox/media/image-attachments/'),
        ),
        migrations.AlterField(
            model_name='qrextendeddevice',
            name='photo',
            field=models.ImageField(upload_to='opt/netbox/netbox/media/image-attachments/'),
        ),
        migrations.AlterField(
            model_name='qrextendedrack',
            name='photo',
            field=models.ImageField(upload_to='opt/netbox/netbox/media/image-attachments/'),
        ),
    ]
