# Generated by Django 3.1.7 on 2021-04-04 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0122_standardize_name_length'),
        ('netbox_qrcode', '0005_auto_20210404_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrextendedcable',
            name='cable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dcim.cable'),
        ),
        migrations.AlterField(
            model_name='qrextendeddevice',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dcim.device'),
        ),
        migrations.AlterField(
            model_name='qrextendedrack',
            name='rack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dcim.rack'),
        ),
    ]
