# Generated by Django 3.1.7 on 2021-04-04 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0122_standardize_name_length'),
        ('netbox_qrcode', '0007_remove_qrextendeddevice_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrextendeddevice',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dcim.device'),
        ),
        migrations.AlterField(
            model_name='qrextendedcable',
            name='cable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dcim.cable'),
        ),
        migrations.AlterField(
            model_name='qrextendedrack',
            name='rack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dcim.rack'),
        ),
    ]
