# Generated by Django 3.1.7 on 2021-04-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_qrcode', '0009_auto_20210404_0513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrextendeddevice',
            name='device_ptr',
        ),
        migrations.AddField(
            model_name='qrextendeddevice',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
