# Generated by Django 3.1.7 on 2021-04-04 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0122_standardize_name_length'),
        ('netbox_qrcode', '0010_auto_20210404_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrextendeddevice',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dcim.device'),
        ),
    ]
