# Generated by Django 3.1.7 on 2021-04-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_qrcode', '0011_qrextendeddevice_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrextendedcable',
            name='photo',
            field=models.ImageField(upload_to='image-attachments/'),
        ),
        migrations.AlterField(
            model_name='qrextendeddevice',
            name='photo',
            field=models.ImageField(upload_to='image-attachments/'),
        ),
        migrations.AlterField(
            model_name='qrextendedrack',
            name='photo',
            field=models.ImageField(upload_to='image-attachments/'),
        ),
    ]
