# Generated by Django 3.1.7 on 2021-04-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_qrcode', '0012_auto_20210404_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrextendedcable',
            name='url',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='qrextendeddevice',
            name='url',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='qrextendedrack',
            name='url',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
    ]
