# Generated by Django 3.1.7 on 2021-04-05 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_qrcode', '0013_auto_20210405_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrextendedcable',
            name='url',
        ),
        migrations.RemoveField(
            model_name='qrextendeddevice',
            name='url',
        ),
        migrations.RemoveField(
            model_name='qrextendedrack',
            name='url',
        ),
    ]
