# Generated by Django 3.1.7 on 2021-04-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_qrcode', '0014_auto_20210405_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrextendedcable',
            name='url',
            field=models.URLField(default='http://localhost:8000/media/image-attachments/modelDevice.png'),
        ),
        migrations.AddField(
            model_name='qrextendeddevice',
            name='url',
            field=models.URLField(default='http://localhost:8000/media/image-attachments/modelDevice.png'),
        ),
        migrations.AddField(
            model_name='qrextendedrack',
            name='url',
            field=models.URLField(default='http://localhost:8000/media/image-attachments/modelDevice.png'),
        ),
    ]
