# Generated by Django 3.1.7 on 2021-04-05 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0122_standardize_name_length'),
        ('netbox_qrcode', '0016_auto_20210405_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrextendeddevice',
            name='new_device_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dcim.devicerole'),
        ),
        migrations.AddField(
            model_name='qrextendeddevice',
            name='new_device_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dcim.devicetype'),
        ),
        migrations.AddField(
            model_name='qrextendeddevice',
            name='new_rack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dcim.rack'),
        ),
        migrations.AddField(
            model_name='qrextendeddevice',
            name='new_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dcim.site'),
        ),
    ]
