# Generated by Django 3.1.7 on 2021-04-05 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_qrcode', '0017_auto_20210405_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrextendeddevice',
            old_name='new_device_role',
            new_name='device_role',
        ),
        migrations.RenameField(
            model_name='qrextendeddevice',
            old_name='new_device_type',
            new_name='device_type',
        ),
        migrations.RenameField(
            model_name='qrextendeddevice',
            old_name='new_rack',
            new_name='rack',
        ),
        migrations.RenameField(
            model_name='qrextendeddevice',
            old_name='new_site',
            new_name='site',
        ),
    ]
