# Generated by Django 3.1.7 on 2021-04-05 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0122_standardize_name_length'),
        ('netbox_qrcode', '0018_auto_20210405_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrextendedrack',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dcim.rackgroup'),
        ),
        migrations.AddField(
            model_name='qrextendedrack',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='qrextendedrack',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dcim.rackrole'),
        ),
        migrations.AddField(
            model_name='qrextendedrack',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dcim.site'),
        ),
    ]
