# Generated by Django 3.1.7 on 2021-04-08 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0122_standardize_name_length'),
        ('netbox_qrcode_ui', '0023_qrextendedrack_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrextendedcable',
            name='cable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dcim.cable'),
        ),
        migrations.AlterField(
            model_name='qrextendeddevice',
            name='device_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dcim.devicerole'),
        ),
        migrations.AlterField(
            model_name='qrextendeddevice',
            name='device_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dcim.devicetype'),
        ),
        migrations.AlterField(
            model_name='qrextendeddevice',
            name='rack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dcim.rack'),
        ),
        migrations.AlterField(
            model_name='qrextendeddevice',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dcim.site'),
        ),
        migrations.AlterField(
            model_name='qrextendedrack',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dcim.rackrole'),
        ),
        migrations.AlterField(
            model_name='qrextendedrack',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dcim.site'),
        ),
    ]
