# Generated by Django 3.1.7 on 2021-04-08 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_qrcode', '0026_auto_20210408_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrextendedcable',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='qrextendeddevice',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
